### ISSUE TITLE
To do: Melhorias SIMA 

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/aura#13]
- [x] Criar _seed_ para cadastro de órgãos; (@gabrielbdornas)
- [x] Criar _seed_ para cadastro de sistemas; (@gabrielbdornas)
   - [x] Siafi
   - [x] Siad
   - [x] Sisap
   - [x] GRP
   - [x] SDAK
   - [x] SIAUT
   - [x] PCNET
   - [x] Portal de Compras
   - [x] Sei
- [x] Run migrations para sistemas
- [ ] Definir o que vai ficar no display do admin
- [ ] Definir o que vai ficar model create form on django admin (how to configure a model create form on django admin app - p/ prompt GPT)
- [x] Incluir no readme instrução de acesso (site +admin)

**Comment by raianecardoso** [comment]
## Webnar 09.ago.2024

**Feedback equipe**
- [ ] Na lista de órgãos:  não pode ter mais de um órgão; 
- [ ] Para o curso, tem que ser possível salvar o projeto do curso sem a oportunidade associada;
- [ ] Incluir curso na origem da demanda;

**Comment by raianecardoso** [comment]
Lembrar que ao fazer cada alteração, é necessário rodar as migrações para que as alterações sejam reproduzidas no banco. Ou seja:

1. pull  
2. Altero documento 
3. Confere com o servidor ligado 
4. Fazer migrações (task makemigrations // task --list)
5. Migrar (task migrate)
6.  Commit 
7.  push na branch de melhorias

**Comment by gabrielbdornas** [comment]
> * Erro 500 do servidor;

@raianecardoso, para o teste tanto na aws quanto em nosso servidor local, seria interessante utilizarmos docker e docker-compose[^1]. Achei [este tutorial](https://www.youtube.com/playlist?list=PLOLrQ9Pn6cazCfL7v4CdaykNoWMQymM_C) bem interessante para descobrirmos como. 

Hoje tivemos uma reunião com pessoal da Subdigital na qual ficou alinhado a utilização do contrato da Microsoft para criação de VMs na Azure. Assim que voltar de férias vou tentar resolver este problema, de maneira definitiva, em uma máquina dessas.

[^1]: Assim ficaria mais fácil de levantar a aplicação e o banco de uma vez só.

**Comment by gabrielbdornas** [comment]
@raianecardoso, pensando em dar um gás no SIMA essa semana de retorno das férias. Alguma novidade nessas 3 semanas?

**Comment by raianecardoso** [comment]
(venv) ➜  sima git:(to-do-melhorias) ✗ task migrate
Traceback (most recent call last):
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "aws-0-sa-east-1.pooler.supabase.com" (15.229.150.166), port 6543 failed: FATAL:  Tenant or user not found
connection to server at "aws-0-sa-east-1.pooler.supabase.com" (15.229.150.166), port 6543 failed: FATAL:  Tenant or user not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/manage.py", line 22, in <module>
    main()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1617, in check
    *cls._check_constraints(databases),
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/models/base.py", line 2467, in _check_constraints
    connection.features.supports_nulls_distinct_unique_constraints
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/postgresql/features.py", line 141, in is_postgresql_15
    return self.connection.pg_version >= 150000
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 438, in pg_version
    with self.temporary_connection():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 691, in temporary_connection
    with self.cursor() as cursor:
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/raianecardoso/Documents/code/automatiza-mg/sima/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "aws-0-sa-east-1.pooler.supabase.com" (15.229.150.166), port 6543 failed: FATAL:  Tenant or user not found
connection to server at "aws-0-sa-east-1.pooler.supabase.com" (15.229.150.166), port 6543 failed: FATAL:  Tenant or user not found

**Comment by gabrielbdornas** [comment]
@raianecardoso, dei uma limpada gigantesca nas tabelas. Não briga comigo, mas fiz uma coisa muito feia e injustificada (por favor nunca repita isso), mas fiquei com preguiça e fiz um mega commit!. Acho que segunda poderíamos tentar fazer o cadastro do projeto da scap no local para ajustes finais.

Achei que ficou bem legal viu!

**Comment by raianecardoso** [comment]
- [x] Inlcuir opção 'unico' como opção de periodicidade em pedido_imersao_models.

**Comment by gabrielbdornas** [comment]
@raianecardoso, podemos fechar este Issue?

**Comment by raianecardoso** [comment]
> @raianecardoso, podemos fechar este Issue?

Sim, fechando agora mesmo! 🎉
